name: main

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'The release tag to deploy'
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name || github.event.inputs.tag }}
      BUILD_NUMBER: $(date +%Y%m%d%H%M%S)
    steps:
      - run: |
        echo "${RELEASE_TAG}"
        echo "${BUILD_NUMBER}"
